window.myFunction = ->
  numPeople = parseInt($('#numPeople').val())
  startingSum = parseInt($('#startingSum').val())
  iterations = parseInt($('#iterations').val())
  demurragePercent = parseInt($('#demurragePercent').val())
  transactPercent = parseInt($('#transactPercent').val())
  transPerIter = parseInt($('#transPerIter').val())
  transactionFund = 0
  accounts = []
  table = $('<table></table>')

  addRow = ->
    row = $('<tr></tr>')
    total = accounts.reduce((a, b) ->
      a + b
    ) + transactionFund

    average = (a) ->
      r = 
        mean: 0
        variance: 0
        deviation: 0
      t = a.length
      m = undefined
      s = 0
      l = t
      while l--
        s += a[l]
      m = r.mean = s / t
      l = t
      s = 0
      while l--
        s += (a[l] - m) ** 2
      r.deviation = Math.sqrt(r.variance = s / t)
      r

    #function calcVariance() {
    #
    #    var x = 0;
    #    for (var i=0;i<numPeople;i++){
    #        x += (accounts[i]-startingSum)^2;
    #    }
    #    return Math.sqrt((1/(numPeople-1))*x)
    #}
    x = average(accounts)
    row.append $('<td>' + transactionFund.toFixed(2) + '</td>')
    i = 0
    while i < numPeople
      row.append $('<td>' + accounts[i].toFixed(2) + '</td>')
      i++
    table.append row
    return

  generatePrice = ->
    x = Math.floor(Math.random() * 150 + 1)
    if x > 50 and x <= 100
      x = x / 2
    if x > 100
      x -= 50
    x

  randomTransaction = ->
    customer = Math.floor(Math.random() * numPeople)
    payee = Math.floor(Math.random() * numPeople)
    while payee == customer
      payee = Math.floor(Math.random() * numPeople)
    price = generatePrice()
    if accounts[customer] >= price
      accounts[customer] -= price
      transTax = price * transactPercent / 100
      transTax = transTax
      transactionFund += transTax
      accounts[payee] += price - transTax
      console.log 'Giving ' + price + ' from ' + customer + ' to ' + payee
    return

  redistribute = ->
    redist = transactionFund / numPeople
    i = 0
    while i < numPeople
      accounts[i] += redist
      i++
    transactionFund = 0
    return

  demurrage = ->
    `var i`
    i = 0
    while i < numPeople
      if accounts[i] > startingSum
        dem = accounts[i] * demurragePercent * 0.01
        accounts[i] -= dem
        transactionFund += dem
      i++
    return

  $('#results').prepend table
  row = $('<tr></tr>')
  row.append '<th>Transaction Fund</th>'
  i = 0
  while i < numPeople
    row.append $('<th>' + i + '</th>')
    accounts.push startingSum
    i++
  table.append row
  i = 0
  while i < iterations
    addRow()
    redistribute()
    j = 0
    while j < transPerIter
      randomTransaction()
      j++
    demurrage()
    i++
  return

# ---
# generated by js2coffee 2.0.4